### PR TITLE
possible to post to hipchat.

### PR DESCRIPTION
**Pull request by nabetama**
It is possible to post to HipChat.

### CODE REVIEW

**Comment by satoshun** [comment]
great pr! but go 1.5 and 1.6 can not use context package. so travis test fails. 

please modify .travis.yml as follows.

```
   include:
-    - go: 1.5
-    - go: 1.6
     - go: 1.7

 install:
```

want to remove 1.5 and 1.6 test.

**Comment by nabetama** [comment]
@satoshun I forgot to check the test results in Travis CI. I excluded 1.5 and 1.6 from the test case.
I though, is it better to use other versions using `runtime.Version()` ?

**Comment by satoshun** [comment]
i think Go1.7 is ok. cuz updating Go is not hard.

**Comment by nabetama** [comment]
If so, I would be happy to merge. 😄

**Comment by satoshun** [comment]
thx😊

**Pull request merged**
